# Development configuration
name = "habctl"

[web]
static_path = "../habux/dist"
listen_addr = "0.0.0.0:8080"
update_interval = 1000

[hardware.mppt.big]
port = "/dev/serial/by-id/usb-VictronEnergy_BV_VE_Direct_cable_VE46V0KW-if00-port0"

[hardware.mppt.lil]
port = "/dev/serial/by-id/usb-VictronEnergy_BV_VE_Direct_cable_VE47E73U-if00-port0"
